### ISSUE TITLE
Density optimization according to ConstraintSystem's OptimizationGoal

### ISSUE THREAD

**Issue by weikengchen** [arkworks-rs/nonnative#29]
Now, one who wants to generate the constraint system in a way that minimizes the weight can indicate this preference in ConstraintSystem's OptimizationGoal. 

This means that, `nonnative` should no longer use a feature `density-optimized` to switch between constraint-optimized and weight-optimized.

Many changes are needed for this issue:
- Decide the parameters based on ConstraintSystem's OptimizationGoal.
- Benchmark for both cases, without the need of indicating the feature.
- Test for both cases.

As for the upstream, this change needs to be propagated to the current `constraints` branch of `poly-commit` and `marlin`.

**Comment by weikengchen** [comment]
Some attempts have been made, but there is one obstacle.

Many data structures in this repo implement `ToConstraintField`. When we do it over a constant structure, we don't know that constraint system, and there is no way to get one.

An example is here at https://github.com/arkworks-rs/nonnative/blob/master/src/nonnative_field_var.rs#L439

```
impl<TargetField: PrimeField, BaseField: PrimeField> ToConstraintFieldGadget<BaseField>
    for NonNativeFieldVar<TargetField, BaseField>
{
    #[tracing::instrument(target = "r1cs")]
    fn to_constraint_field(&self) -> R1CSResult<Vec<FpVar<BaseField>>> {
        match self {
            Self::Constant(c) => Ok(AllocatedNonNativeFieldVar::get_limbs_representations(c)?
                .into_iter()
                .map(FpVar::constant)
                .collect()),
            Self::Var(v) => v.to_constraint_field(),
        }
    }
}
```

There seem to be no better ways unless we require all constant elements to additionally store a constraint system. For example,
```
/// A gadget for representing non-native (`TargetField`) field elements over the constraint field (`BaseField`).
#[derive(Clone, Debug)]
#[must_use]
pub enum NonNativeFieldVar<TargetField: PrimeField, BaseField: PrimeField> {
    /// Constant
    Constant(TargetField),
    /// Allocated gadget
    Var(AllocatedNonNativeFieldVar<TargetField, BaseField>),
}
```
where we may need to change `Constant(TargetField)` to include also a constraint system ref under the BaseField.

------

This move, however, might be necessary. Since one who imports the repo must stick to only one type of optimization.

Any suggestion @Pratyush ?

**Comment by Pratyush** [comment]
And the issue is that we need the size of the vec output by `ToConstraintField` to match in both cases? Why not normalize to the most packed representation and use that? I.e, convert to bytes, and then pack the bytes into field elements? It would be slightly more expensive, but IMO it's worth it

**Comment by weikengchen** [comment]
I agree. Let me think about a way to make the `ToConstraintField` unspecific to the type. Adding the OptimizationType to Constant created additional overhead.
